import { createHash } from "node:crypto";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  CRATES_IO_DOWNLOAD,
  CRATES_IO_INDEX,
  DependencyPrefetchError,
  hermeticCargoConfig,
  hermeticGitConfig,
  indexPath,
  parseCargoLock,
  planDependencies,
  prefetchCargoDependencies,
  type FetchHttps,
  type RunCommand,
} from "./cargo-prefetch";
import { assertPublicHttpsRepoUrl } from "./repo-url-guard";

const CRATE_BYTES = Buffer.from("fake crate archive");
const CRATE_SUM = createHash("sha256").update(CRATE_BYTES).digest("hex");
const COMMIT = "50981ccd5d2de654cf0e50633919cc9ba2df4e58";
const COMMIT_2 = "0123456789abcdef0123456789abcdef01234567";

function lockfile(...packages: string[]): string {
  return [
    "# This file is automatically @generated by Cargo.",
    "version = 4",
    "",
    ...packages,
    "",
    "[[patch.unused]]",
    'name = "ignored"',
    'version = "1.0.0"',
  ].join("\n");
}

const localPkg = `[[package]]
name = "my-contract"
version = "0.1.0"
dependencies = [
 "itoa",
 "smart-wallet-interface",
]`;

const itoaPkg = `[[package]]
name = "itoa"
version = "1.0.15"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "${CRATE_SUM}"`;

const gitPkg = (commit = COMMIT, url = "https://github.com/kalepail/passkey-kit") => `[[package]]
name = "smart-wallet-interface"
version = "1.0.0"
source = "git+${url}?rev=${commit}#${commit}"`;

describe("parseCargoLock", () => {
  it("reads [[package]] tables and skips arrays, comments and other tables", () => {
    const pkgs = parseCargoLock(lockfile(localPkg, itoaPkg, gitPkg()));
    expect(pkgs).toEqual([
      { name: "my-contract", version: "0.1.0" },
      {
        name: "itoa",
        version: "1.0.15",
        source: "registry+https://github.com/rust-lang/crates.io-index",
        checksum: CRATE_SUM,
      },
      {
        name: "smart-wallet-interface",
        version: "1.0.0",
        source: `git+https://github.com/kalepail/passkey-kit?rev=${COMMIT}#${COMMIT}`,
      },
    ]);
  });

  it("refuses values it cannot read unambiguously", () => {
    expect(() =>
      parseCargoLock(lockfile('[[package]]\nname = "a\\"b"\nversion = "1.0.0"')),
    ).toThrow(DependencyPrefetchError);
    expect(() => parseCargoLock(lockfile('[[package]]\nversion = "1.0.0"'))).toThrow(
      /without a name/,
    );
  });
});

describe("planDependencies", () => {
  it("splits crates.io and git sources and needs nothing for path deps", () => {
    const plan = planDependencies(parseCargoLock(lockfile(localPkg, itoaPkg, gitPkg())));
    expect(plan.registry).toEqual([{ name: "itoa", version: "1.0.15", checksum: CRATE_SUM }]);
    expect(plan.git).toHaveLength(1);
    expect(plan.git[0]).toMatchObject({
      url: "https://github.com/kalepail/passkey-kit",
      commits: [COMMIT],
    });
  });

  it("accepts the sparse crates.io source form", () => {
    const plan = planDependencies([
      {
        name: "itoa",
        version: "1.0.15",
        source: "sparse+https://index.crates.io/",
        checksum: CRATE_SUM,
      },
    ]);
    expect(plan.registry).toHaveLength(1);
  });

  it("keeps one mirror per git URL, holding every locked commit", () => {
    const plan = planDependencies([
      { name: "a", version: "1.0.0", source: `git+https://github.com/o/r?branch=main#${COMMIT}` },
      {
        name: "b",
        version: "1.0.0",
        source: `git+https://github.com/o/r?rev=${COMMIT_2}#${COMMIT_2}`,
      },
      { name: "c", version: "1.0.0", source: `git+https://github.com/o/r#${COMMIT}` },
    ]);
    expect(plan.git).toHaveLength(1);
    expect(plan.git[0]!.commits).toEqual([COMMIT, COMMIT_2]);
    expect(plan.git[0]!.url).toBe("https://github.com/o/r");
  });

  it.each([
    ["an alternate registry", "registry+https://evil.example/index"],
    ["a sparse alternate registry", "sparse+https://evil.example/index/"],
    ["an unknown source kind", "path+file:///etc"],
  ])("refuses %s", (_label, source) => {
    expect(() =>
      planDependencies([{ name: "x", version: "1.0.0", source, checksum: CRATE_SUM }]),
    ).toThrow(expect.objectContaining({ code: "dependencies_unresolved" }));
  });

  it("refuses a crates.io package without a sha256 checksum", () => {
    expect(() =>
      planDependencies([
        {
          name: "itoa",
          version: "1.0.15",
          source: "registry+https://github.com/rust-lang/crates.io-index",
        },
      ]),
    ).toThrow(/no sha256 checksum/);
  });

  it("refuses a git dependency not pinned to a full commit", () => {
    expect(() =>
      planDependencies([
        { name: "a", version: "1.0.0", source: "git+https://github.com/o/r?branch=main" },
      ]),
    ).toThrow(/not pinned to a full commit/);
  });

  it("refuses names and versions that are not path-safe", () => {
    expect(() =>
      planDependencies([
        {
          name: "../x",
          version: "1.0.0",
          source: "sparse+https://index.crates.io/",
          checksum: CRATE_SUM,
        },
      ]),
    ).toThrow(/invalid name or version/);
    expect(() =>
      planDependencies([
        {
          name: "x",
          version: "1.0/../../0",
          source: "sparse+https://index.crates.io/",
          checksum: CRATE_SUM,
        },
      ]),
    ).toThrow(/invalid name or version/);
  });

  it("refuses git URLs that could not be written into git config verbatim", () => {
    expect(() =>
      planDependencies([
        { name: "a", version: "1.0.0", source: `git+https://github.com/o/r"x#${COMMIT}` },
      ]),
    ).toThrow(/not valid/);
  });
});

describe("indexPath", () => {
  it.each([
    ["a", "1/a"],
    ["ab", "2/ab"],
    ["abc", "3/a/abc"],
    ["Soroban-SDK", "so/ro/soroban-sdk"],
  ])("%s → %s", (name, path) => expect(indexPath(name)).toBe(path));
});

describe("hermetic build config", () => {
  it("replaces crates.io with the read-only local registry and uses the git CLI", () => {
    const cfg = hermeticCargoConfig();
    expect(cfg).toContain('[source.crates-io]\nreplace-with = "vellar-prefetched"');
    expect(cfg).toContain('local-registry = "/deps/registry"');
    expect(cfg).toContain("git-fetch-with-cli = true");
  });

  it("rewrites every locked git URL to its mirror and allows only the file transport", () => {
    const plan = planDependencies(parseCargoLock(lockfile(gitPkg())));
    const cfg = hermeticGitConfig(plan);
    expect(cfg).toContain("[protocol]\n\tallow = never");
    expect(cfg).toContain('[protocol "file"]\n\tallow = always');
    expect(cfg).toContain(
      `[url "file:///deps/git/${plan.git[0]!.mirrorId}"]\n\tinsteadOf = "https://github.com/kalepail/passkey-kit"`,
    );
  });
});

describe("prefetchCargoDependencies", () => {
  let repoDir: string;
  let depsDir: string;

  beforeEach(async () => {
    repoDir = await mkdtemp(join(tmpdir(), "prefetch-repo-"));
    depsDir = await mkdtemp(join(tmpdir(), "prefetch-deps-"));
  });
  afterEach(async () => {
    await rm(repoDir, { recursive: true, force: true });
    await rm(depsDir, { recursive: true, force: true });
  });

  const publicPin = async (url: string) => ({
    host: new URL(url).hostname,
    port: 443,
    ip: "151.101.1.137",
  });

  // A crates.io stand-in: serves the index line + archive for itoa 1.0.15 and
  // records every request so tests can see where the pre-fetch went.
  function fakeCratesIo(overrides: { index?: number; crate?: number; body?: Buffer } = {}) {
    const requests: { url: string; pinnedIp?: string }[] = [];
    const fetchHttps: FetchHttps = async (url, pin) => {
      requests.push({ url: url.toString(), pinnedIp: pin?.ip });
      if (url.toString().startsWith(CRATES_IO_INDEX)) {
        if (overrides.index) return { status: overrides.index, body: Buffer.alloc(0) };
        const line = JSON.stringify({ name: "itoa", vers: "1.0.15", deps: [], cksum: CRATE_SUM });
        const other = JSON.stringify({
          name: "itoa",
          vers: "1.0.14",
          deps: [],
          cksum: "0".repeat(64),
        });
        return { status: 200, body: Buffer.from(`${other}\n${line}\n`) };
      }
      if (overrides.crate) return { status: overrides.crate, body: Buffer.alloc(0) };
      return { status: 200, body: overrides.body ?? CRATE_BYTES };
    };
    return { fetchHttps, requests };
  }

  // git stand-in: every command succeeds unless scripted otherwise.
  function fakeGit(opts: { fetchCode?: number; hasCommit?: boolean; submodules?: boolean } = {}) {
    const calls: string[][] = [];
    const run: RunCommand = async (cmd, args) => {
      calls.push([cmd, ...args]);
      if (args.includes("fetch")) return { code: opts.fetchCode ?? 0, out: "fetch output" };
      if (args[0] === "cat-file" && args[2]?.endsWith("^{commit}"))
        return { code: opts.hasCommit === false ? 1 : 0, out: "" };
      if (args[0] === "cat-file" && args[2]?.endsWith(":.gitmodules"))
        return { code: opts.submodules ? 0 : 128, out: "" };
      return { code: 0, out: "" };
    };
    return { run, calls };
  }

  it("fails with dependencies_unresolved when Cargo.lock is missing", async () => {
    const { run } = fakeGit();
    await expect(prefetchCargoDependencies(repoDir, depsDir, { run })).rejects.toMatchObject({
      code: "dependencies_unresolved",
      message: expect.stringMatching(/Cargo\.lock is missing/),
    });
  });

  it("writes the locked index line and the checksum-verified crate to the local registry", async () => {
    await writeFile(join(repoDir, "Cargo.lock"), lockfile(localPkg, itoaPkg));
    const { fetchHttps, requests } = fakeCratesIo();
    const { run } = fakeGit();
    const result = await prefetchCargoDependencies(repoDir, depsDir, {
      run,
      fetchHttps,
      assertUrl: publicPin,
    });

    expect(result.plan.registry).toHaveLength(1);
    const index = await readFile(join(depsDir, "registry", "index", "it", "oa", "itoa"), "utf8");
    expect(index.trim().split("\n")).toHaveLength(1);
    expect(JSON.parse(index).vers).toBe("1.0.15");
    expect(await readFile(join(depsDir, "registry", "itoa-1.0.15.crate"))).toEqual(CRATE_BYTES);
    // Only the two fixed crates.io hosts, each pinned to the guard's address.
    expect(requests.map((r) => r.url)).toEqual([
      `${CRATES_IO_INDEX}/it/oa/itoa`,
      `${CRATES_IO_DOWNLOAD}/itoa/itoa-1.0.15.crate`,
    ]);
    expect(requests.every((r) => r.pinnedIp === "151.101.1.137")).toBe(true);
  });

  it("refuses a crate whose bytes do not match the Cargo.lock checksum", async () => {
    await writeFile(join(repoDir, "Cargo.lock"), lockfile(itoaPkg));
    const { fetchHttps } = fakeCratesIo({ body: Buffer.from("tampered") });
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, {
        run: fakeGit().run,
        fetchHttps,
        assertUrl: publicPin,
      }),
    ).rejects.toMatchObject({
      code: "dependencies_unresolved",
      message: expect.stringMatching(/checksum/),
    });
  });

  it("refuses a locked version crates.io does not publish", async () => {
    await writeFile(
      join(repoDir, "Cargo.lock"),
      lockfile(itoaPkg.replace('version = "1.0.15"', 'version = "9.9.9"')),
    );
    const { fetchHttps } = fakeCratesIo();
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, {
        run: fakeGit().run,
        fetchHttps,
        assertUrl: publicPin,
      }),
    ).rejects.toMatchObject({
      code: "dependencies_unresolved",
      message: expect.stringMatching(/not published/),
    });
  });

  it("maps a 404 to dependencies_unresolved and a 5xx / network error to dependency_fetch_failed", async () => {
    await writeFile(join(repoDir, "Cargo.lock"), lockfile(itoaPkg));
    const run = fakeGit().run;
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, {
        run,
        fetchHttps: fakeCratesIo({ index: 404 }).fetchHttps,
        assertUrl: publicPin,
      }),
    ).rejects.toMatchObject({ code: "dependencies_unresolved" });
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, {
        run,
        fetchHttps: fakeCratesIo({ crate: 503 }).fetchHttps,
        assertUrl: publicPin,
      }),
    ).rejects.toMatchObject({ code: "dependency_fetch_failed" });
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, {
        run,
        fetchHttps: async () => {
          throw new Error("ECONNRESET");
        },
        assertUrl: publicPin,
      }),
    ).rejects.toMatchObject({ code: "dependency_fetch_failed" });
  });

  it("does not follow redirects: a 30x is a failure, not a new destination", async () => {
    await writeFile(join(repoDir, "Cargo.lock"), lockfile(itoaPkg));
    const { fetchHttps, requests } = fakeCratesIo({ crate: 302 });
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, {
        run: fakeGit().run,
        fetchHttps,
        assertUrl: publicPin,
      }),
    ).rejects.toBeInstanceOf(DependencyPrefetchError);
    expect(requests).toHaveLength(2);
  });

  it("mirrors a git dependency through the pinned, redirect-free, https-only fetch", async () => {
    await writeFile(join(repoDir, "Cargo.lock"), lockfile(gitPkg()));
    const { run, calls } = fakeGit();
    const guard = (url: string) =>
      assertPublicHttpsRepoUrl(url, { resolve: async () => ["140.82.121.3"] });
    await prefetchCargoDependencies(repoDir, depsDir, { run, assertUrl: guard });

    const fetch = calls.find((c) => c.includes("fetch"))!;
    expect(fetch).toContain("protocol.allow=never");
    expect(fetch).toContain("protocol.https.allow=always");
    expect(fetch).toContain("http.followRedirects=false");
    expect(fetch).toContain("http.curloptResolve=github.com:443:140.82.121.3");
    const sep = fetch.indexOf("--");
    expect(fetch.slice(sep + 1)).toEqual([
      "https://github.com/kalepail/passkey-kit",
      `+${COMMIT}:refs/heads/vellar-locked-0`,
    ]);
  });

  // H2 regression: the dependency graph must not open a new unguarded path.
  it.each([
    ["cloud metadata", "https://metadata.example/r", ["169.254.169.254"]],
    ["loopback", "https://internal.example/r", ["127.0.0.1"]],
    ["RFC1918", "https://intranet.example/r", ["10.0.0.5"]],
    ["mixed public+private answers", "https://rebind.example/r", ["93.184.216.34", "192.168.1.1"]],
  ])(
    "rejects a git dependency resolving to %s before any git command",
    async (_l, url, answers) => {
      await writeFile(join(repoDir, "Cargo.lock"), lockfile(gitPkg(COMMIT, url)));
      const { run, calls } = fakeGit();
      const guard = (u: string) => assertPublicHttpsRepoUrl(u, { resolve: async () => answers });
      await expect(
        prefetchCargoDependencies(repoDir, depsDir, { run, assertUrl: guard }),
      ).rejects.toMatchObject({
        code: "repo_url_rejected",
      });
      expect(calls).toHaveLength(0);
    },
  );

  it.each([
    ["ssh", "ssh://git@github.com/o/r"],
    ["plain http", "http://github.com/o/r"],
    ["an IP literal in a private range", "https://10.1.2.3/o/r"],
    ["embedded credentials", "https://user:pw@github.com/o/r"],
  ])("rejects a %s git dependency (repo-url-guard)", async (_l, url) => {
    await writeFile(join(repoDir, "Cargo.lock"), lockfile(gitPkg(COMMIT, url)));
    const { run, calls } = fakeGit();
    const guard = (u: string) =>
      assertPublicHttpsRepoUrl(u, { resolve: async () => ["140.82.121.3"] });
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, { run, assertUrl: guard }),
    ).rejects.toMatchObject({
      code: "repo_url_rejected",
    });
    expect(calls).toHaveLength(0);
  });

  it("RA-7: an IPv6-literal git dependency is refused before the guard is consulted", async () => {
    // The hex-form mapped-loopback gap in isBlockedAddress is never reached: the
    // bracketed literal fails the URL check, so no DNS, guard or git runs.
    await writeFile(
      join(repoDir, "Cargo.lock"),
      lockfile(gitPkg(COMMIT, "https://[::ffff:7f00:1]/o/r")),
    );
    const { run, calls } = fakeGit();
    const guarded: string[] = [];
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, {
        run,
        assertUrl: (u) => {
          guarded.push(u);
          return assertPublicHttpsRepoUrl(u);
        },
      }),
    ).rejects.toMatchObject({ code: "dependencies_unresolved" });
    expect(guarded).toHaveLength(0);
    expect(calls).toHaveLength(0);
  });

  it("refuses a git dependency with submodules (their URLs are not in Cargo.lock)", async () => {
    await writeFile(join(repoDir, "Cargo.lock"), lockfile(gitPkg()));
    const { run } = fakeGit({ submodules: true });
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, { run, assertUrl: publicPin }),
    ).rejects.toMatchObject({
      code: "dependencies_unresolved",
      message: expect.stringMatching(/submodules/),
    });
  });

  it("fails when the locked commit cannot be fetched", async () => {
    await writeFile(join(repoDir, "Cargo.lock"), lockfile(gitPkg()));
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, {
        run: fakeGit({ fetchCode: 128 }).run,
        assertUrl: publicPin,
      }),
    ).rejects.toMatchObject({ code: "dependency_fetch_failed" });
    await expect(
      prefetchCargoDependencies(repoDir, depsDir, {
        run: fakeGit({ hasCommit: false }).run,
        assertUrl: publicPin,
      }),
    ).rejects.toMatchObject({ code: "dependencies_unresolved" });
  });
});
